export const UPDATE_APPLY_EMAIL_VALUE = 'UPDATE_APPLICATION_EMAIL';
export type UPDATE_APPLY_EMAIL = typeof UPDATE_APPLY_EMAIL_VALUE;

export const UPDATE_APPLY_FIRST_NAME_VALUE = 'UPDATE_APPLICATION_FIRST_NAME';
export type UPDATE_APPLY_FIRST_NAME = typeof UPDATE_APPLY_FIRST_NAME_VALUE;

export const UPDATE_APPLY_LAST_NAME_VALUE = 'UPDATE_APPLICATION_LAST_NAME';
export type UPDATE_APPLY_LAST_NAME = typeof UPDATE_APPLY_LAST_NAME_VALUE;

export const UPDATE_APPLY_ORGANIZATION_VALUE = 'UPDATE_APPLICATION_ORGANIZATION';
export type UPDATE_APPLY_ORGANIZATION = typeof UPDATE_APPLY_ORGANIZATION_VALUE;

export const UPDATE_APPLY_DESCRIPTION_VALUE = 'UPDATE_APPLICATION_DESCRIPTION';
export type UPDATE_APPLY_DESCRIPTION = typeof UPDATE_APPLY_DESCRIPTION_VALUE;

export const UPDATE_APPLY_CLIENT_TYPE_VALUE =
  'UPDATE_APPLICATION_OAUTH_APPLICATION_TYPE';
export type UPDATE_APPLY_OAUTH_APPLICATION_TYPE = typeof UPDATE_APPLY_CLIENT_TYPE_VALUE;

export const UPDATE_APPLY_REDIRECT_URI_VALUE = 'UPDATE_APPLICATION_OAUTH_REDIRECT_URI';
export type UPDATE_APPLY_OAUTH_REDIRECT_URI = typeof UPDATE_APPLY_REDIRECT_URI_VALUE;

export const TOGGLE_SELECTED_API_VALUE = 'TOGGLE_SELECTED_API';
export type TOGGLE_SELECTED_API = typeof TOGGLE_SELECTED_API_VALUE;

export const SUBMIT_APPLICATION_BEGIN_VALUE = 'SUBMIT_APPLICATION_BEGIN';
export type SUBMIT_APPLICATION_BEGIN = typeof SUBMIT_APPLICATION_BEGIN_VALUE;

export const SUBMIT_APPLICATION_SUCCESS_VALUE = 'SUBMIT_APPLICATION_SUCCESS';
export type SUBMIT_APPLICATION_SUCCESS = typeof SUBMIT_APPLICATION_SUCCESS_VALUE;

export const SUBMIT_APPLICATION_ERROR_VALUE = 'SUBMIT_APPLICATION_ERROR';
export type SUBMIT_APPLICATION_ERROR = typeof SUBMIT_APPLICATION_ERROR_VALUE;

export const TOGGLE_ACCEPT_TOS_VALUE = 'TOGGLE_ACCEPT_TOS';
export type TOGGLE_ACCEPT_TOS = typeof TOGGLE_ACCEPT_TOS_VALUE;
