export const LOAD_CATEGORY_CONTENT_VALUE = 'LOAD_CATEGORY_CONTENT';
export type LOAD_CATEGORY_CONTENT = typeof LOAD_CATEGORY_CONTENT_VALUE;

export const SET_CATEGORY_CONTENT_VALUE = 'SET_CATEGORY_CONTENT';
export type SET_CATEGORY_CONTENT = typeof SET_CATEGORY_CONTENT_VALUE;

export const LOAD_API_CONTENT_VALUE = 'LOAD_API_CONTENT';
export type LOAD_API_CONTENT = typeof LOAD_API_CONTENT_VALUE;

export const SET_API_CONTENT_VALUE = 'SET_API_CONTENT';
export type SET_API_CONTENT = typeof SET_API_CONTENT_VALUE;
