export const RESET_GENERAL_STORE_VALUE = 'RESET_GENERAL_STORE';
export type RESET_GENERAL_STORE = typeof RESET_GENERAL_STORE_VALUE;

export const SET_GENERAL_STORE_VALUE = 'SET_GENERAL_STORE';
export type SET_GENERAL_STORE = typeof SET_GENERAL_STORE_VALUE;
