export const SET_SCROLL_POSITION_VALUE = 'SET_SCROLL_POSITION_VALUE';
export type SET_SCROLL_POSITION = typeof SET_SCROLL_POSITION_VALUE;
export const RESET_SCROLL_POSITION_VALUE = 'RESET_SCROLL_POSITION_VALUE';
export type RESET_SCROLL_POSITION = typeof RESET_SCROLL_POSITION_VALUE;
