export const SET_REQUESTED_API_VERSION = 'SET_REQUESTED_APIVERSION';
export type SET_REQUESTED_API_VERSION = typeof SET_REQUESTED_API_VERSION;

export const SET_VERSIONING = 'SET_VERSIONING';
export type SET_VERSIONING = typeof SET_VERSIONING;
